name: Python Task

on:
  

  workflow_dispatch:
    inputs:
      repo:
        required: true
      owner:
        required: true
      environment:
        required: true
jobs:
  #Checkout-Job:
   # uses: Omairkhalid95/Reusable_workflow/.github/workflows/main.yml@reuse
  build:
    runs-on: 
      - self-hosted
      - test
     
    steps:
    - name: Git Checkout
      uses: actions/checkout@v2
    - name: Updated Variables
      uses: cschleiden/replace-tokens@v1
      with:
        tokenPrefix: __
        tokenSuffix: __
        files: '["./python.py"]'
      env:
        repo: ${{ github.event.inputs.repo }}
        owner: ${{ github.event.inputs.owner }}
        environment: ${{ github.event.inputs.environment }}

    

       


 
    
